### ISSUE TITLE
QuickCarpet no longer compatible with Fabric API

### ISSUE THREAD

**Issue by Arrowpuppet** [QuickCarpet/QuickCarpet#129] opened 2022-02-19 18:34 UTC
**Versions**
- Minecraft: 1.18.1
- QuickCarpet: 3.3.0+1.18

**Describe the bug**
QuickCarpet causes the game to crash on launch with Fabric API versions past 0.45.0+1.18.

**To Reproduce**
1. Install QuickCarpet 3.3.0+1.18 alongside Fabric API version 0.45.1+1.18 or later
2. Launch Minecraft
3. Game crashes on launch.

**Expected behavior**
These two mods should be compatible with each other; installing Fabric API 0.45.0 works completely fine with QuickCarpet.

**Logs**
https://pastebin.com/e2Ny9wN6

**Comment by skyrising** [comment] 2022-02-19 18:35
Duplicate of #124 already fixed in the development builds (see Actions)

**Closed by skyrising** 2022-02-19 18:35 UTC
Labels: bug
