### ISSUE TITLE
Fabric Compatibility

### ISSUE THREAD

**Issue by exdocious** [QuickCarpet/QuickCarpet#128] opened 2022-02-09 04:32 UTC
I cant launch Quick carpet on 1.18.1

I understand that this is caused by Fabric API but is there any version of the API that works for 1.18.1

or do you have any indication that can help with when this will be resolved

**1.18.1**
- Minecraft: QuickCarpet Skyblock
- QuickCarpet: quickcarpet-3.3.0+1.18

**Crash report**
```
[06:28:47] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.13.1
[06:28:47] [main/WARN]: Warnings were found!
 - Mod 'QuickCarpet' (quickcarpet) 3.3.0 recommends version 0.10.0-dev.23 of malilib, which is missing!
	 - You should install version 0.10.0-dev.23 of malilib for the optimal experience.
[06:28:47] [main/INFO]: Loading 52 mods:
	- fabric 0.46.4+1.18
	- fabric-api-base 0.4.2+d7c144a865 via fabric
	- fabric-api-lookup-api-v1 1.5.3+d7c144a865 via fabric
	- fabric-biome-api-v1 6.0.2+d7c144a865 via fabric
	- fabric-blockrenderlayer-v1 1.1.10+3ac43d9565 via fabric
	- fabric-command-api-v1 1.1.7+d7c144a865 via fabric
	- fabric-commands-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-containers-v0 0.1.19+d7c144a865 via fabric
	- fabric-content-registries-v0 0.4.8+d7c144a865 via fabric
	- fabric-crash-report-info-v1 0.1.9+3ac43d9565 via fabric
	- fabric-dimensions-v1 2.1.10+a1d9bbf565 via fabric
	- fabric-entity-events-v1 1.4.6+d7c144a865 via fabric
	- fabric-events-interaction-v0 0.4.17+d7c144a865 via fabric
	- fabric-events-lifecycle-v0 0.2.9+d7c144a865 via fabric
	- fabric-game-rule-api-v1 1.0.11+d7c144a865 via fabric
	- fabric-item-api-v1 1.3.1+691a79b565 via fabric
	- fabric-item-groups-v0 0.3.6+3ac43d9565 via fabric
	- fabric-key-binding-api-v1 1.0.9+d7c144a865 via fabric
	- fabric-keybindings-v0 0.2.7+b4f4f6cd65 via fabric
	- fabric-lifecycle-events-v1 1.4.13+713c266865 via fabric
	- fabric-loot-tables-v1 1.0.9+d7c144a865 via fabric
	- fabric-mining-level-api-v1 1.0.6+d7c144a865 via fabric
	- fabric-mining-levels-v0 0.1.11+b4f4f6cd65 via fabric
	- fabric-models-v0 0.3.4+d7c144a865 via fabric
	- fabric-networking-api-v1 1.0.19+d7c144a865 via fabric
	- fabric-networking-v0 0.3.6+b4f4f6cd65 via fabric
	- fabric-object-builder-api-v1 1.11.4+d7c144a865 via fabric
	- fabric-object-builders-v0 0.7.12+d7c144a865 via fabric
	- fabric-particles-v1 0.2.10+526dc1ac65 via fabric
	- fabric-registry-sync-v0 0.9.2+ad01bfbd65 via fabric
	- fabric-renderer-api-v1 0.4.11+b0b66fc365 via fabric
	- fabric-renderer-indigo 0.4.15+6825030165 via fabric
	- fabric-renderer-registries-v1 3.2.10+b4f4f6cd65 via fabric
	- fabric-rendering-data-attachment-v1 0.3.5+d7c144a865 via fabric
	- fabric-rendering-fluids-v1 0.1.19+3ac43d9565 via fabric
	- fabric-rendering-v0 1.1.12+b4f4f6cd65 via fabric
	- fabric-rendering-v1 1.10.6+713c266865 via fabric
	- fabric-resource-conditions-api-v1 1.0.2+d7c144a865 via fabric
	- fabric-resource-loader-v0 0.4.14+713c266865 via fabric
	- fabric-screen-api-v1 1.0.8+d7c144a865 via fabric
	- fabric-screen-handler-api-v1 1.1.12+d7c144a865 via fabric
	- fabric-structure-api-v1 2.1.3+d7c144a865 via fabric
	- fabric-tag-extensions-v0 1.2.8+d7c144a865 via fabric
	- fabric-textures-v0 1.0.10+3ac43d9565 via fabric
	- fabric-tool-attribute-api-v1 1.3.8+fb3b57b465 via fabric
	- fabric-transfer-api-v1 1.5.9+d7c144a865 via fabric
	- fabricloader 0.13.1
	- java 17
	- minecraft 1.18.1
	- quickcarpet 3.3.0
	- quickcarpet-api 1.1.0 via quickcarpet
	- skyblock 3.2.1
[06:28:47] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/exdoc/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.1+mixin.0.8.5/sponge-mixin-0.11.1+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[06:28:47] [main/INFO]: Compatibility level set to JAVA_16
[06:28:48] [main/INFO]: Applying Fabric API Registry Sync workaround
[06:28:48] [main/WARN]: Error loading class: net/minecraft/class_1949 (java.lang.ClassNotFoundException: net/minecraft/class_1949)
[06:28:48] [main/WARN]: @Mixin target net.minecraft.class_1949 was not found quickcarpet.mixins.json:tileTickLimit.ServerTickSchedulerMixin
[06:28:51] [main/ERROR]: Mixin apply for mod quickcarpet failed quickcarpet.mixins.json:fabricApi.RegistrySyncManagerMixin -> net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Redirect annotation on redirectGetRegistry could not find any targets matching 'Lnet/fabricmc/fabric/impl/registry/sync/RegistrySyncManager;toTag(ZLnet/minecraft/class_2487;)Lnet/minecraft/class_2487;' in net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager. Using refmap quickcarpet-refmap.json [PREINJECT Applicator Phase -> quickcarpet.mixins.json:fabricApi.RegistrySyncManagerMixin -> Prepare Injections ->  -> redirect$zkn000$redirectGetRegistry(Lnet/minecraft/class_2378;Lnet/minecraft/class_2960;)Ljava/lang/Object; -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Redirect annotation on redirectGetRegistry could not find any targets matching 'Lnet/fabricmc/fabric/impl/registry/sync/RegistrySyncManager;toTag(ZLnet/minecraft/class_2487;)Lnet/minecraft/class_2487;' in net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager. Using refmap quickcarpet-refmap.json [PREINJECT Applicator Phase -> quickcarpet.mixins.json:fabricApi.RegistrySyncManagerMixin -> Prepare Injections ->  -> redirect$zkn000$redirectGetRegistry(Lnet/minecraft/class_2378;Lnet/minecraft/class_2960;)Ljava/lang/Object; -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.RedirectInjectionInfo.<init>(RedirectInjectionInfo.java:44) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) [fabric-loader-0.13.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) [fabric-loader-0.13.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) [fabric-loader-0.13.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) [?:?]
	at net.minecraft.class_2370.onChange(class_2370.java:1058) [client-intermediary.jar:?]
	at net.minecraft.class_2370.handler$zep000$set(class_2370.java:1053) [client-intermediary.jar:?]
	at net.minecraft.class_2370.method_10273(class_2370.java:66) [client-intermediary.jar:?]
	at net.minecraft.class_2370.method_10272(class_2370.java:97) [client-intermediary.jar:?]
	at net.minecraft.class_2378.method_10227(class_2378.java:321) [client-intermediary.jar:?]
	at net.minecraft.class_2378.method_29109(class_2378.java:312) [client-intermediary.jar:?]
	at net.minecraft.class_2378.method_10224(class_2378.java:304) [client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:170) [client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:155) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.1.jar:?]
[06:28:51] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:418) ~[fabric-loader-0.13.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.1.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:155) ~[fabric-loader-0.13.1-1.18.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.1.jar:?]
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252) ~[fabric-loader-0.13.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2370.onChange(class_2370.java:1058) ~[client-intermediary.jar:?]
	at net.minecraft.class_2370.handler$zep000$set(class_2370.java:1053) ~[client-intermediary.jar:?]
	at net.minecraft.class_2370.method_10273(class_2370.java:66) ~[client-intermediary.jar:?]
	at net.minecraft.class_2370.method_10272(class_2370.java:97) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.method_10227(class_2378.java:321) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.method_29109(class_2378.java:312) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.method_10224(class_2378.java:304) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:170) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:155) ~[fabric-loader-0.13.1-1.18.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.1.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2370.onChange(class_2370.java:1058) ~[client-intermediary.jar:?]
	at net.minecraft.class_2370.handler$zep000$set(class_2370.java:1053) ~[client-intermediary.jar:?]
	at net.minecraft.class_2370.method_10273(class_2370.java:66) ~[client-intermediary.jar:?]
	at net.minecraft.class_2370.method_10272(class_2370.java:97) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.method_10227(class_2378.java:321) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.method_29109(class_2378.java:312) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.method_10224(class_2378.java:304) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:170) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:155) ~[fabric-loader-0.13.1-1.18.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.1.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [quickcarpet.mixins.json:fabricApi.RegistrySyncManagerMixin] from phase [DEFAULT] in config [quickcarpet.mixins.json] from mod [quickcarpet] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2370.onChange(class_2370.java:1058) ~[client-intermediary.jar:?]
	at net.minecraft.class_2370.handler$zep000$set(class_2370.java:1053) ~[client-intermediary.jar:?]
	at net.minecraft.class_2370.method_10273(class_2370.java:66) ~[client-intermediary.jar:?]
	at net.minecraft.class_2370.method_10272(class_2370.java:97) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.method_10227(class_2378.java:321) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.method_29109(class_2378.java:312) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.method_10224(class_2378.java:304) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:170) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:155) ~[fabric-loader-0.13.1-1.18.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.1.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Redirect annotation on redirectGetRegistry could not find any targets matching 'Lnet/fabricmc/fabric/impl/registry/sync/RegistrySyncManager;toTag(ZLnet/minecraft/class_2487;)Lnet/minecraft/class_2487;' in net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager. Using refmap quickcarpet-refmap.json [PREINJECT Applicator Phase -> quickcarpet.mixins.json:fabricApi.RegistrySyncManagerMixin -> Prepare Injections ->  -> redirect$zkn000$redirectGetRegistry(Lnet/minecraft/class_2378;Lnet/minecraft/class_2960;)Ljava/lang/Object; -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.RedirectInjectionInfo.<init>(RedirectInjectionInfo.java:44) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.1+mixin.0.8.5.jar:0.11.1+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2370.onChange(class_2370.java:1058) ~[client-intermediary.jar:?]
	at net.minecraft.class_2370.handler$zep000$set(class_2370.java:1053) ~[client-intermediary.jar:?]
	at net.minecraft.class_2370.method_10273(class_2370.java:66) ~[client-intermediary.jar:?]
	at net.minecraft.class_2370.method_10272(class_2370.java:97) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.method_10227(class_2378.java:321) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.method_29109(class_2378.java:312) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.method_10224(class_2378.java:304) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:170) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:155) ~[fabric-loader-0.13.1-1.18.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.1.jar:?]
	... 2 more

```

**Comment by skyrising** [comment] 2022-02-09 15:24
This is a duplicate of #124

**Closed by skyrising** 2022-02-09 15:24 UTC
Labels: bug
