### ISSUE TITLE
tick warp + invenoty preview 

### ISSUE THREAD

**Issue by SpirinW** [QuickCarpet/QuickCarpet#100] opened 2021-07-19 21:40 UTC
**Versions**
- Minecraft: 1.17.1 fabric
- QuickCarpet: quickcarpet-3.1.1+1.17

**Crash report**
[crash-2021-07-14_03.58.12-server.txt](https://github.com/QuickCarpet/QuickCarpet/files/6844059/crash-2021-07-14_03.58.12-server.txt)

```
Paste either the crash report (found in .minecraft/crash-reports/) or latest.log (found in .minecraft/logs/).
Be careful that you remove personal information in case you send latest.log
```

**Comment by skyrising** [comment] 2021-07-19 22:37
This was caused by 1.17.1 changing a few things and fixed in 94c6516824cb31fae74d5f09c1f640aabd8a2c9c. Will be in the next release.

**Closed** 2021-07-19 22:37 UTC
Labels: bug
